### ISSUE TITLE
userId no esta siendo guardado en createQuestion (Viene en jwt)

### ISSUE THREAD

**Issue by jvann** [harusama/Dashed-FrontEnd#1]
Obtener userid de jwt y guardar en question.

<img width="682" alt="screen shot 2018-04-17 at 1 51 33 pm" src="https://user-images.githubusercontent.com/6835119/38890292-994da18c-4246-11e8-92e1-2b688b40a48b.png">
<img width="485" alt="screen shot 2018-04-17 at 1 51 54 pm" src="https://user-images.githubusercontent.com/6835119/38890293-99695738-4246-11e8-9ba0-174135bf5cf1.png">
<img width="461" alt="screen shot 2018-04-17 at 1 52 17 pm" src="https://user-images.githubusercontent.com/6835119/38890294-99851036-4246-11e8-9078-fde8c824ff56.png">

**Comment by ferlopez94** [comment]
Pero el userId lo mandas en el jtw, en el header, ¿no?

**Comment by jvann** [comment]
ahhhh tienes, razon, pero pues igual no se updateo el user
