### ISSUE TITLE
Como funciona approved?

### ISSUE THREAD

**Issue by jvann** [harusama/Dashed-FrontEnd#7]
* Questions approved no tiene un numero para saber cuando fueron aprobados o no, solo hay approved y ya, como funciona?

**Comment by ferlopez94** [comment]
Está el campo `approved_times` que es un counter. Al pasar cierto threshold el campo `approved` se convierte en TRUE. Adicionalmente está la tabla `approvals` que contiene referencia a una pregunta y un user_id quien aprobó cierta pregunta.
